packages:
  - 'apps/*'
  - 'packages/*'
  - 'backend'

catalog:
  # React ecosystem
  react: ^19.0.0
  react-dom: ^19.0.0
  
  # Core tools
  typescript: ^5.7.2
  
  # Validation & types
  zod: ^3.24.1
  
  # Backend
  convex: ^1.18.0
  
  # Auth
  better-auth: ^1.2.5
  
  # Routing
  '@tanstack/react-router': ^1.91.8
  '@tanstack/router-plugin': ^1.91.8
  
  # UI libraries
  '@xyflow/react': ^12.3.6
  recharts: ^2.15.0
  
  # Next.js
  next: ^15.1.4
  
  # Vite
  vite: ^6.0.5
  '@vitejs/plugin-react': ^4.3.4
  
  # Expo/React Native
  expo: ~52.0.0
  react-native: 0.76.5
  nativewind: ^4.1.23
  
  # Build tools
  turbo: ^2.3.3
  
  # Linting & formatting
  eslint: ^9.17.0
  prettier: ^3.4.2
  '@eslint/js': ^9.17.0
  typescript-eslint: ^8.18.1
  eslint-config-prettier: ^9.1.0
  
  # Types
  '@types/react': ^19.0.1
  '@types/react-dom': ^19.0.2
  '@types/node': ^22.10.2

